### ISSUE TITLE
Lag/Freezing

### ISSUE THREAD

**Issue by cz016m** [Marsgames/GearHelper#111]
After the most recent WoW patch 9.1.5, I've noticed some in game lagging/freezing issues when GearHelper is enabled. When I disable GearHelper, the lag/freezing goes away immediately. This hasn't happened before. It happens consistently after the recent 9.1.5 patch. Curious if anyone else is experiencing this issue. It's making it so that I can't use GearHelper, which is one of my favorite addons.

**Comment by Marsgames** [comment]
Hey, 

First of all, thank you for your feedback.

Do you have a precise moment where the game start lagging, or it's as soon as WoW launch ?
Can you try to use /gh resetcache and tell me if anything is better ?

As far as I try, I do not have any lag or freeze. I'll have to investigate more te sue which fonction can cause this issue.

Once again, thank you for your feedbacks, it helps us to improve GearHelper :)

**Comment by cz016m** [comment]
Hello,

The addon seems to cause lag while I'm playing WoW. I believe the GearHelper addon is causing the lag because when I disable the addon and reload my user interface, the lag disappears immediately. I will try the /gh resetcache command and let you know the results. It just seems to freeze up the game for a couple seconds at a time sporadically.

Regards,
Rodney

________________________________

**Comment by MarshallBuhl** [comment]
I, too, have had this problem, but didn't know it might be related to GH until reading this issue.  The lag gradually gets worse as I play--usually after an hour or so.  I have NOT tried disabling GH to see if that solves it.  I've been /EXITing the game and restarting it to clear the lag  That gives me another hour or two of lag-free playing.  The lag sometimes happens at the very worst time and I have died in The Maw many times because of it..  I wondered if it might be a memory leak in WoW, but Task Manager indicates I still have plenty of free RAM.

I have entered "/gh resetcache" and will play for a while to see if it fixes the problem.

**Comment by cz016m** [comment]
Hello, I tried the /gh resetcache but it didn't resolve the lag issue. It happens any time I'm using the addon. It always happens. I love the addon, but I feel like it's ambitious and trying to do too much work and it is causing significant game lag in my powerful gaming system. To that end, I have disabled the addon because the lag is nearly unbearable.

**Comment by Marsgames** [comment]
Hey, can you try usine this command ?
´´´
/gh benchmarkCountResult
´´´
When it starts lagging, it will print a bunch of functions, and how many times there are called. It tell me what are functions the most used, to see what could cause this lags

**Comment by cz016m** [comment]
Hello,

When I type that command, I receive the following error, "Benchmark Mode not enabled ! Use /gh benchmark". So I typed /gh benchmark and pressed enter. I didn't receive any response from the addon, so I assumed it was enabled. You should probably add a confirmation in chat. After the addon started lagging the game, I typed, "/gh benchmarkCountResult" and I got results. However, the output is in my chat box. I don't know how to export it or copy and paste it.

Thank you,
Rodney
________________________________

**Comment by MarshallBuhl** [comment]
I'm still getting lag after "/gh resetcache".

**Comment by MarshallBuhl** [comment]
I tried the "/gh benchmarkCountResult", but was told I had to enable benchmarking with "/gh benchmark".  I did and I got one message immediately, but then no more--even when lagging.

I've been suffering with lag while fishing in STV.  I had turned off autoloot because I hoped to get multiple Waterlogged Journals.  Clicking on the catches and the items in the trunks was very laggy.

I disabled GH and did a "/reload" and my lag problems disappeared immediately.

**Comment by Marsgames** [comment]
I will investigate while fishing. Thank you for your feedbacks

**Comment by MarshallBuhl** [comment]
It didn't lag immediately while fishing.  It started happening after I had been fishing for Weather-Beaten Journals for a while (maybe 0.5-1 hours).

**Comment by cz016m** [comment]
I don't think the lag is related to your in-game activity. It happens to me regardless of what I'm doing, even standing still.

**Comment by cz016m** [comment]
Here are my values: ( had to manually type them)
13628
13628
6497
6480
5698
4799
1920
899
788
498
356
356
356
356
356
356
356
356
356
183
120
115
113
113
113
78
72
61
61
61
61
42
36
21
16
8
8
6
5
4
2
2
2
2
2
1
1

**Comment by MarshallBuhl** [comment]
New data.  When I enable or disable GH, I get the following error when my UI reloads:

Message: ...ard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua:34: attempt to index upvalue 'SuperTrackEventFrame' (a nil value)
Time: Sat Jan 29 15:32:24 2022
Count: 1
Stack: ...ard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua:34: attempt to index upvalue 'SuperTrackEventFrame' (a nil value)
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_QuestSuperTracking.lua"]:34: in function `QuestSuperTracking_ShouldHighlightWorldQuests'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:276: in function `ShouldHighlightInfo'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:433: in function `UpdateSupertrackedHighlight'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:420: in function <...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:401>
[string "=[C]"]: in function `RefreshVisuals'
[string "@Interface\AddOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua"]:49: in function <...dOns\Blizzard_WorldMap\WM_WorldQuestDataProvider.lua:48>
[string "=[C]"]: in function `RefreshVisuals'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:356: in function `AddWorldQuest'
[string "@Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua"]:235: in function <...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:204>
[string "=[C]"]: in function `RefreshAllData'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:627: in function `ToggleWorldMapFrameMixin'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:661: in function `configurationScript22'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:977: in function `?'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:2615: in function `_OnEvent'
[string "@Interface\AddOns\Wholly\Wholly.lua"]:4538: in function <Interface\AddOns\Wholly\Wholly.lua:4538>

Locals: uiMapID = 1565
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'SuperTrackEventFrame' (a nil value)"
SuperTrackEventFrame = nil

**Comment by Marsgames** [comment]
I don't really get why you get this error when you enable or disable GH, but it seems to be caused by Wholly and not GH

**Comment by cz016m** [comment]
What is Wholly? I don't have any addons named Wholly.

**Comment by MarshallBuhl** [comment]
According to Wholly's web site:

"Wholly is a complete visualization of the Grail quest database addon as it relates to the player. It shows a panel with quests conveniently separated into zones and indicates their status. Quests can be filtered so only those that need to be completed, etc. appear. Wholly also shows pins on the world map for locations where quest givers appear, and the pins are similarly colored based on their status."

**Comment by stottieuk** [comment]
Hi to all, 

I been finding it lags after a little while if and when the mouse pointer moves over the spells icons on my bars or any windows with gear eg auction house. or trying when reading information on item or spell.  disabling the addon seems to fix all the lag and reload ui fix it for a while then it come back

Dose the same if run the addon it self with no other addons just blizzard ones
Love the addon

**Comment by MarshallBuhl** [comment]
I had a series of terrible lag events today where my system essentially froze for about a minute before getting this:

Message: Interface\AddOns\GearHelper\GearHelper.lua:429: ...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1
Time: Sun Feb 27 08:41:25 2022
Count: 1
Stack: Interface\AddOns\GearHelper\GearHelper.lua:429: ...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\GearHelper\GearHelper.lua"]:429: in function <Interface\AddOns\GearHelper\GearHelper.lua:374>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1372: in function `ContainerFrameItemButton_OnUpdate'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1419: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = "...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1"

**Comment by MarshallBuhl** [comment]
I just realized that the error I mentioned above is associated with hovering over a shield.  This used to be a constant problem for a long time, but seemed to have been fixed until now.

**Comment by Marsgames** [comment]
I just released a new version, that I hope will resolve the lags/freezes. Let me know if it's fix or not :)

@MarshallBuhl, I tried with few shields and / or off hands items, and I am not able to reproduct issue. I don't have any error while hovering this kind of items

**Comment by cz016m** [comment]
Thank you for the fixes! I have been using the addon all day with no lag 🙂

Rodney
________________________________

**Comment by Marsgames** [comment]
Pleased to know that it worked !

**Comment by MarshallBuhl** [comment]
The shield issue is back:

Message: Interface\AddOns\GearHelper\GearHelper.lua:446: ...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1
Time: Fri Mar 11 22:24:46 2022
Count: 2
Stack: Interface\AddOns\GearHelper\GearHelper.lua:446: ...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\GearHelper\GearHelper.lua"]:446: in function <Interface\AddOns\GearHelper\GearHelper.lua:375>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1372: in function `ContainerFrameItemButton_OnUpdate'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1419: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = "...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1"

**Comment by MarshallBuhl** [comment]
OK.  This just happened on some bracers (a first for something other than a shield):

Message: Interface\AddOns\GearHelper\GearHelper.lua:446: ...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1
Time: Fri Mar 11 22:26:20 2022
Count: 13
Stack: Interface\AddOns\GearHelper\GearHelper.lua:446: ...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\GearHelper\GearHelper.lua"]:446: in function <Interface\AddOns\GearHelper\GearHelper.lua:375>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1372: in function `ContainerFrameItemButton_OnUpdate'
[string "@Interface\FrameXML\ContainerFrame.lua"]:1419: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = "...nterface\AddOns\GearHelper\Gear\GH_TooltipHelper.lua:28: ItemLink is not valid : -1"

**Comment by MarshallBuhl** [comment]
The error with the bracers happened only the first time I hovered over them.  The shield kept doing it.

**Comment by MarshallBuhl** [comment]
OK.  Very strange.  Not gear was involved when I hovered over a recipe with the Dalaran (Northrend) Alchemy trainer and got this error:

Message: Interface\AddOns\GearHelper\GearHelper.lua:481: table index is nil
Time: Sun Mar 13 11:41:38 2022
Count: 15
Stack: Interface\AddOns\GearHelper\GearHelper.lua:481: table index is nil
[string "@Interface\AddOns\GearHelper\GearHelper.lua"]:481: in function <Interface\AddOns\GearHelper\GearHelper.lua:375>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetTrainerService'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>

Locals: self = GameTooltip {
 0 = <userdata>
 SetText = <function> defined =[C]:-1
 SetPvpTalent = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 ARKTTD = <table> {
 }
 SetLootCurrency = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 FadeOut = <function> defined =[C]:-1
 SetQuestLogSpecialItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetSpellByID = <function> defined =[C]:-1
 NineSlice = <unnamed> {
 }
 SetCompanionPet = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetAction = <function> defined =[C]:-1
 SetCurrencyByID = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 Backdrop = GHGameTooltipBackdrop {
 }
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.068000
 SetArtifactPowerByID = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 ClearLines = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetUnitDebuff = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 hasMoney = 1
 SetQuestItem = <function> defined =[C]:-1
 numMoneyFrames = 1
 waitingForData = false
 SetToyByItemID = <function> defined =[C]:-1
 comparing = false
 SetInboxItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetInventoryItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetTalent = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 SetRecipeRankInfo = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined =[C]:-1
 textLeft2Font = "GameTooltipText"
 SetVoidItem = <function> defined =[C]:-1
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 SetItemByID = <function> defined =[C]:-1
 SetItemKey = <function> defined =[C]:-1
 needsReset = true
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetTradeTargetItem = <function> defined =[C]:-1
 SetQuestLogCurrency = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
}
name = nil
itemLink = nil
shouldBeCompared = false
err = "...erface\AddOns\GearHelper\Gear\GH_StatComputation.lua:32: ItemLink is not valid"
linesToAdd = <table> {
}
isItemEquipped = false
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"
tooltipProcessed = <table> {
}
ShouldDisplayNotEquippable = <function> defined @Interface\AddOns\GearHelper\GearHelper.lua:360
L = <table> {
 demande4esES2 = " que acabas de recibir "
 demande2 = " if he needs "
 DNR = "Do not
